projects:
  traffskip:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: 5y2rl3d24zeqrecr6s5omgvs4u
      endpoints:
        prod: >-
          https://visyz533nffi5jahg5jaa64hzq.appsync-api.ap-south-1.amazonaws.com/graphql
